### ISSUE TITLE
Bubble Chart Pack Layout

### ISSUE THREAD

**Issue by orpitadutta** [tomwanzek/d3-ng2-service#70] opened 2017-06-17 04:33 UTC
I am unable to make bubble chart using ng2-d3-service.`

{

let width: number;
let height: number;
let d3ParentElement: Selection<HTMLElement, any, null, undefined>;
let d3Svg: Selection<SVGSVGElement, any, null, undefined>;
var diameter = 600;
var dataset = [
     {Name= "CROWN",
     Count= 2
      }, {
         Name: "KING",
          Count: 2
      }, {
          Name: "QUEEN",
          Count: 1
      }, {
          Name: "CINDERELLA",
          Count: 2
      }, {
          Name: "PRINCE",
          Count: 3
      }, {
          Name: "PRINCESS",
          Count: 1
      }, {
          Name: "WAND",
          Count: 5
      }];

var color = d3.scaleOrdinal(d3.schemeCategory20);
var bubble = d3.pack()
        .size([diameter, diameter])
        .padding(1);

if (this.parentNativeElement !== null) {
  d3ParentElement = d3.select(this.parentNativeElement);
  var d3Svgdemo = d3ParentElement.select(".chart").append("svg")
        .attr("width", diameter)
        .attr("height", diameter)
        .attr("class", "bubble");
        var nodes = d3.hierarchy(dataset)
        .sum(function(d: any) { return d.Count; });

var node = d3Svgdemo.selectAll(".node")
        .data(bubble(nodes).descendants())
        .enter()
        .filter(function(d){
            return  !d.children
        })
        .append("g")
        .attr("class", "node")
        .attr("transform", function(d) {
          console.log(d.x + "" + d.y)
            return "translate(" + d.x + "," + d.y + ")";
        });

node.append("title")
        .text(function(d:any) {
            return d.data.Name + ": " + d.data.Count;
        });

node.append("circle")
        .attr("r", function(d) {
            return d.r;
        })
        .style("fill", function(d:any) {
            return color(d.data.Name);
        });

node.append("text")
        .attr("dy", ".3em")
        .style("text-anchor", "middle")
        .text(function(d:any) {
            return d.data.Name.substring(0, d.r / 3) + ": " + d.data.Count;
        });
}

**Comment by tomwanzek** [comment] 2017-06-19 13:12
Duplicate of #69

**Closed by tomwanzek** 2017-06-19 13:12 UTC
Labels: duplicate
